### ISSUE TITLE
[Request] Configurable aspects for Nodes

### ISSUE THREAD

**Issue by spannerman79** [KryptonCaptain/MagicBees#1]
Is it possible to have a value set in the config for the value `255` within https://github.com/KryptonCaptain/MagicBees/blob/1.7.10-krypt/src/main/java/magicbees/main/utils/compat/thaumcraft/NodeHelper.java#L113 to be able to be pulled from a setting within the MagicBees.cfg?

Non java dev example would be to replace `while (aspectsBase.getAmount(aspectToAdd) > 255 && rollAttempts < 20);`  with `while (aspectsBase.getAmount(aspectToAdd) > ( maxAspects -1) && rollAttempts < 20);`

`maxAspects` being defined in the config that is the maximum amount of aspects to be added to the node, default being 256 - keeping in line with the intended change done by MagicBees devs but allow for people to go back to super nodes (like https://i.imgur.com/7Ety75u.png )

**Comment by KryptonCaptain** [comment]
Yeah, I can do that pretty easily

**Comment by KryptonCaptain** [comment]
Aight, head on over to Releases

**Comment by spannerman79** [comment]
Thank you _very_ much!
